POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4OTMxMDU5MzFjMzQ2Yjc0NDQ0NDkxOCIsImlhdCI6MTc1NDQ2ODc0NX0.ZK7MzYRgtZsNpmb97CVIwuO822rrwYa7YtbgnZ4hhDc

{
  "title": "Test Blog",
  "author": "Li TianSuo",
  "url": "https://www.bilibili.com/",
  "likes": 114514
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer Wrong

{
  "title": "FullStackOpen",
  "author": "Matti Luukkainen",
  "url": "https://fullstackopen.com/",
  "likes": 2022
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4OGNiODg0NDRkMjQ1Y2Y5NzJkNjlhYiIsImlhdCI6MTc1NDA1NTQyMn0.7Kei8CFSJzYtQqae9h3GejKV7DL3YJ-CRc1vDzui878

{
  "title": "FullStackOpen",
  "author": "Matti Luukkainen",
  "url": "https://fullstackopen.com/",
  "likes": 2022
}