POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test Blog",
  "author": "Li TianSuo",
  "url": "https://www.bilibili.com",
  "likes": 114514,
  "userId": "688cb88444d245cf972d69ab"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "FullStackOpen",
  "author": "Matti Luukkainen",
  "url": "https://fullstackopen.com",
  "likes": 2022,
  "userId": "688cb88444d245cf972d69ab"
}