POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Test User",
  "password": "114514"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "aa",
  "name": "Wrong User",
  "password": "1919180"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "abcd",
  "name": "Wrong User",
  "password": "19"
}