POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "114514"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "wrong"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "root2",
  "password": "1919180"
}